# Use the official OpenJDK 21 JDK slim image as the base image.
# This image provides a lightweight runtime environment for Java 21 applications.
FROM openjdk:21-jdk-slim

# Set the working directory inside the container to /app.
# All subsequent operations will be performed in this directory.
WORKDIR /app

# Copy the JAR file generated by Maven (usually located in the target directory)
# to the working directory inside the container and rename it to app.jar.
COPY target/trans_demo-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose port 8080, which is the default port for Spring Boot applications.
# This is mainly for documentation purposes and tools like Docker Compose to understand the port usage.
EXPOSE 8080

# Define the command to be executed when the container starts.
# Use the 'java -jar' command to run the Spring Boot application.
CMD ["java", "-jar", "app.jar"]